title: "World Bank Reproducible Research Repository"
description: "Guidance to Authors, Checklist, Reviewer Protocol, and Tools for reproducibility."
remote_theme: pages-themes/cayman@v0.2.0

# URL settings
url: "https://worldbank.github.io"
baseurl: "/wb-reproducible-research-repository"  # This matches your repo name

# Enable plugins for remote themes
plugins:
  - jekyll-remote-theme

# Optional: Define your header pages for navigation
header_pages:
  - index.md
  - guidance_note_wb.md
  - reproducibility_package_checklist.md
  - reproducibility_reviewer_protocol.md
  - reproducible_research_trainings.md

