title: "World Bank Reproducible Research Repository"
description: "Guidance to Authors, Checklist, Reviewer Protocol, and Tools for reproducibility."
remote_theme: mmistakes/minimal-mistakes
baseurl: ""  # Keep this empty
url: "https://worldbank.github.io/wb-reproducible-research-repository"  # Replace with your GitHub username and repository name

# Navigation settings for the menu
header_pages:
  - index.md
  - guidance_note_wb.md
  - reproducibility_package_checklist.md
  - reproducibility_reviewer_protocol.md
  - reproducible_research_trainings.md